
[package]
name     = "vulkan-base"
version  = "0.0.1"
authors  = ["usami-renko <usami-ssc@protonmail.com>"]
edition  = "2018"
keywords = ["Vulkan", "Rust", "Graphics"]
description = "An library to provide convenient methods to access vulkan."

[dependencies]
ash   = "0.27.1"
winit = "0.18.0"
